#!/bin/bash

finished=0

while [ $finished -ne 1 ]
do

echo "Enter your favorite Linux Destro:- "
echo "1- Arch"
echo "2- CentOS"
echo "3- Debian"
echo "4- Mint"
echo "5- Ubuntu"
echo "6- Something else ..."
echo "7- Exit the script.. "

read var
case $var in 
        1) echo "Arch is a rolling release";;
	2) echo "CentOS is popular on servers";;
	3) echo "Debian is a community distribution";;
	4) echo "Mint is popular on desktops and laptops";;
	5) echo "Ubuntu is popular on both servers and desktops";;
	6) echo "There are many distributions out there";;
	7) finished=1
		echo "Thank you for using the script";;
	*) echo "You didn't enter an appropriate choice";;
esac
done
