#!/bin/bash

echo "Enter the package to check"
read file

func () {
if [ -f /usr/bin/$file ] 
then
	echo " Package is available "
else 
	echo "Package is not available, do you want to install it ? "
	read -p " Do you want to search and install the packet? Enter yes or no :- " user_input

	if [ "$user_input" == "yes" ]
	then
		sudo dnf install $file
	elif [ "$user_input" == "no" ]
	then
		echo "Package check cancelled"
	else
	        echo "Your input is invalid.."
	fi
	fi
}

func

echo "Enter the package to check"
read file
func

echo "Enter the package to check"
read file
func
